ARG BASE_IMAGE="debian"
ARG BASE_VERSION="bookworm"

FROM ${BASE_IMAGE}:${BASE_VERSION}

ARG USER="gbraad"
ARG HOMEBASE="/home"
ARG USERHOME="${HOMEBASE}/${USER}"
ARG ROOTHOME="/root"
ARG ARCH="amd64"

LABEL org.opencontainers.image.source = "https://github.com/gbraad-dotfiles/debian"

RUN apt update \
    && apt install -y \
        systemd \
	    init \
        sudo \
        git \
        curl \
    && apt install -y \
        ansible \
    && rm -rf /var/lib/apt/lists/*

RUN useradd -l -u 1000 -G sudo -md ${USERHOME} -p ${USER} ${USER} \
    && sed -i.bkp -e '/Defaults\tuse_pty/d' -e 's/%sudo\s\+ALL=(ALL\(:ALL\)\?)\s\+ALL/%sudo ALL=NOPASSWD:ALL/g' /etc/sudoers

USER ${USER}

RUN git clone https://github.com/gbraad-dotfiles/upstream.git ${USERHOME}/.dotfiles --depth 2 \
    && cd ${USERHOME}/.dotfiles \
    && bash ./install.sh

# public keys for SSH login
RUN mkdir -p ${USERHOME}/.ssh/ \
    && curl https://github.com/${USER}.keys | tee -a ${USERHOME}/.ssh/authorized_keys \
    && curl https://dotfiles.gbraad.nl/public.keys | tee -a ${USERHOME}/.ssh/authorized_keys

USER root

RUN git clone https://github.com/gbraad-dotfiles/upstream.git ${ROOTHOME}/.dotfiles --depth 2 \
    && mkdir -p ${ROOTHOME}/.config \
    && cd ${ROOTHOME}/.dotfiles \
    && . ./dotfiles.sh \
    && stow config \
    && dotfiles restow

RUN chsh -s /usr/bin/zsh ${USER} \
    && chsh -s /usr/bin/zsh

# install tailscale (or use https://github.com/spotsnel/tailscale-systemd/)
RUN curl -fsSL https://pkgs.tailscale.com/stable/debian/bookworm.noarmor.gpg -o /usr/share/keyrings/tailscale-archive-keyring.gpg \
    && curl -fsSL https://pkgs.tailscale.com/stable/debian/bookworm.tailscale-keyring.list | sudo tee /etc/apt/sources.list.d/tailscale.list \
    && apt update \
    && apt install -y \
        tailscale \
    && rm -rf /var/lib/apt/lists/* \
    && mkdir -p /var/run/tailscale /var/cache/tailscale /var/lib/tailscale
# already 'enabled' by default
#   && systemctl enable tailscaled

# install cloudflared (or use https://github.com/spotsnel/cloudflared-systemd/)
RUN curl -fsSL https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-${ARCH}.deb -o /tmp/cloudflared.deb \
    && apt install -y \
        /tmp/cloudflared.deb \
    && rm -f /tmp/cloudflared.deb \
    && rm -rf /var/lib/apt/lists/*

# enable linger for the user (loginctl won't work without systemd running)
RUN mkdir -p /var/lib/systemd/linger \
    && touch /var/lib/systemd/linger/${USER}

# Enable systemd
ENTRYPOINT [ "/sbin/init" ]
