ARG BASE_IMAGE="registry.access.redhat.com/ubi9-init"
ARG BASE_VERSION="9.5"

FROM ${BASE_IMAGE}:${BASE_VERSION}

ARG USER="gbraad"
ARG USER_PASSWD
ARG HOMEBASE="/home"
ARG USERHOME="${HOMEBASE}/${USER}"
ARG ROOTHOME="/root"
ARG ARCH="x86_64"

# fix issue with sudo and SSH
RUN chmod 640 /etc/shadow

RUN dnf install -y \
        sudo \
        git \
        dnf-plugins-core \
    && dnf install -y \
        util-linux \
        util-linux-user \
    && dnf install -y \
        https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm \
    && ARCH=$( [ "$ARCH" = "amd64" ] && echo "x86_64" || ( [ "$ARCH" = "arm64" ] && echo "aarch64" ) ) \
    && dnf install -y \
        https://mirror.stream.centos.org/9-stream/BaseOS/${ARCH}/os/Packages/tmux-3.2a-5.el9.${ARCH}.rpm \
    && dnf clean all \
    && rm -rf /var/cache/yum

# fix for PAM/SSH
RUN chmod 0640 /etc/shadow

RUN useradd -l -u 1000 -G wheel -md ${USERHOME} -s /bin/bash -p ${USER} ${USER} \
    && sed -i.bkp -e 's/%wheel\s\+ALL=(ALL\(:ALL\)\?)\s\+ALL/%wheel ALL=NOPASSWD:ALL/g' /etc/sudoers \
    && if [ -n "${USER_PASSWD}" ] ; then \
        echo "gbraad:${USER_PASSWD}" | sudo chpasswd && echo "Password set to: ${USER_PASSWD}"; \
    fi

USER ${USER}

RUN git clone https://github.com/gbraad-dotfiles/upstream.git ${USERHOME}/.dotfiles --depth 2 \
    && cd ${USERHOME}/.dotfiles \
    && rm -f ${USERHOME}/.zshrc \
    && sh ./install.sh

RUN mkdir -p ~/.ssh/ \
    && curl https://github.com/${USER}.keys | tee -a ~/.ssh/authorized_keys

USER root

RUN git clone https://github.com/gbraad-dotfiles/upstream.git ${ROOTHOME}/.dotfiles --depth 2 \
    && mkdir -p ${ROOTHOME}/.config \
    && cd ${ROOTHOME}/.dotfiles \
    && source ./dotfiles.sh \
    && stow config \
    && dotfiles restow

RUN chsh -s /usr/bin/zsh ${USER} \
    && chsh -s /usr/bin/zsh

# install tailscale (or use https://github.com/spotsnel/tailscale-systemd/)
RUN dnf config-manager --add-repo https://pkgs.tailscale.com/stable/rhel/9/tailscale.repo \
    && dnf install -y \
        tailscale \
    && dnf clean all \
    && rm -rf /var/cache/yum \
    && mkdir -p /var/run/tailscale /var/cache/tailscale /var/lib/tailscale \
    && systemctl enable tailscaled

# install cloudflared (or use https://github.com/spotsnel/cloudflared-systemd/)
RUN dnf install -y \
        systemd \
    && ARCH=$( [ "$ARCH" = "amd64" ] && echo "x86_64" || ( [ "$ARCH" = "arm64" ] && echo "aarch64" ) ) \
    && curl -fsSL https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-${ARCH}.rpm -o /tmp/cloudflared.rpm \
    && dnf install -y \
        /tmp/cloudflared.rpm \
    && dnf clean all \
    && rm -rf /var/cache/yum \
    && rm -f /tmp/cloudflared.rpm

# enable linger for the user (loginctl won't work without systemd running)
RUN mkdir -p /var/lib/systemd/linger \
    && touch /var/lib/systemd/linger/${USER}

# Enable systemd
ENTRYPOINT [ "/sbin/init" ]
