name: reusable-build-container

on:
  workflow_call:
    inputs:
      container_name:
        description: "Name of the container (e.g., fedora, ubi9)"
        required: true
        type: string
      arch:
        description: "Architecture for the container (e.g., arm64, amd64)"
        required: true
        type: string
    secrets:
      GITHUB_TOKEN:
        description: "GitHub token for authentication"

jobs:
  build:
    name: Build Container
    runs-on: ${{ inputs.arch == 'arm64' && 'ubuntu-24.04-arm' || 'ubuntu-latest' }}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Fetch shared configuration
        uses: gbraad-actions/shared-config@v1
        with:
          config_repo: https://github.com/gbraad-dotfiles/shared-config.git
          config_file: actions/${{ inputs.container_name }}.ini

      - name: Build container
        run: |
          containerfile_path=".devcontainer/${{ inputs.container_name }}/Containerfile"
          podman build -t ghcr.io/${{ github.repository }}/${{ inputs.container_name }}:${{ inputs.arch }} \
            --build-arg=BASE_IMAGE="${{ env.BASE_IMAGE }}" \
            --build-arg=BASE_VERSION="${{ env.BASE_VERSION }}" \
            --build-arg=ARCH="${{ inputs.arch }}" \
            -f "$containerfile_path"

      - name: Save container as OCI
        run: |
          podman save ghcr.io/${{ github.repository }}/${{ inputs.container_name }}:${{ inputs.arch }} \
            --format=oci-dir -o oci-${{ inputs.arch }}

      - uses: actions/upload-artifact@v4
        with:
          name: oci-${{ inputs.arch }}
          path: oci-${{ inputs.arch }}/
          retention-days: 7

      - name: Run podman export
        run: |
          podman create --name ${{ inputs.container_name }}-${{ inputs.arch }} \
            ghcr.io/${{ github.repository }}/${{ inputs.container_name }}:${{ inputs.arch }}
          podman export ${{ inputs.container_name }}-${{ inputs.arch }} -o ${{ inputs.container_name }}-${{ inputs.arch }}.tar
          gzip ${{ inputs.container_name }}-${{ inputs.arch }}.tar

      - uses: actions/upload-artifact@v4
        with:
          name: rootfs-${{ inputs.arch }}
          path: ${{ inputs.container_name }}-${{ inputs.arch }}.tar.gz
          retention-days: 7