name: Build and Push Fedora Bootable Container

on:
  workflow_dispatch:

jobs:
  build-amd64:
    name: Build Fedora Bootable Container (amd64)
    uses: ./.github/workflows/reusable-build-container-bootc.yml
    with:
      container_name: "fedora-bootc"
      arch: "amd64"
    secrets: inherit

  push-manifest:
    name: Push Multi-Architecture Manifest
    uses: ./.github/workflows/reusable-push-manifest.yml
    needs:
      - build-amd64
    with:
      container_name: "fedora-bootc"
      archs: '["amd64"]'
    secrets: inherit
