name: Build and Push Fedora Container

on:
  workflow_dispatch:

jobs:
  build-arm64:
    name: Build Fedora Container (arm64)
    uses: ./.github/workflows/reusable/build-container.yml
    with:
      container_name: "fedora"
      arch: "arm64"
    secrets: inherit

  build-amd64:
    name: Build Fedora Container (amd64)
    uses: ./.github/workflows/reusable/build-container.yml
    with:
      container_name: "fedora"
      arch: "amd64"
    secrets: inherit

  push-manifest:
    name: Push Multi-Architecture Manifest
    uses: ./.github/workflows/reusable/push-manifest.yml
    needs:
      - build-arm64
      - build-amd64
    with:
      container_name: "fedora"
      archs: '["arm64","amd64"]'
      version: "41"
    secrets: inherit
