name: Build and Push OpenSUSE cloud diskimage

on:
  workflow_dispatch:


jobs:
  build-diskimage-opensuse-machine:
    uses: ./.github/workflows/reusable-build-diskimage-machine.yml
    with:
      container_name: opensuse-cloud
      base_image: opensuse/tumbleweed
      base_version: latest
    secrets: inherit
