name: Build and Push Debian cloud diskimage
on:
  push:
    branches:
      - "main"
  schedule:
    - cron: "0 0 */2 * *"
  workflow_dispatch:


jobs:
  build-diskimage-debian-machine:
    uses: ./.github/workflows/reusable-build-diskimage-machine.yml
    with:
      container_name: debian-cloud
