name: Build and Push UBI9 Container

on:
  workflow_dispatch:

jobs:
  build-arm64:
    name: Build UBI9 Container (arm64)
    uses: ./.github/workflows/reusable/build-container.yml
    with:
      container_name: "ubi9"
      arch: "arm64"
    secrets: inherit

  build-amd64:
    name: Build UBI9 Container (amd64)
    uses: ./.github/workflows/reusable/build-container.yml
    with:
      container_name: "ubi9"
      arch: "amd64"
    secrets: inherit

  push-manifest:
    name: Push Multi-Architecture Manifest
    uses: ./.github/workflows/reusable/push-manifest.yml
    needs:
      - build-arm64
      - build-amd64
    with:
      container_name: "ubi9"
      archs: "arm64,amd64"
    secrets: inherit
