name: build diskimage containers
run-name: Building diskimage containers
on:
  schedule:
    - cron: "0 0 */2 * *"
  workflow_dispatch:

jobs:
  trigger-build-diskimage-almalinux:
    runs-on: ubuntu-latest
    steps:
      - name: Start AlmaLinux diskimage build
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'build-diskimage-almalinux.yml',
              ref: context.ref,
            });

  trigger-build-diskimage-centos:
    runs-on: ubuntu-latest
    steps:
      - name: Start CentOS diskimage build
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'build-diskimage-centos.yml',
              ref: context.ref,
            });

  trigger-build-diskimage-fedora:
    runs-on: ubuntu-latest
    steps:
      - name: Start Fedora diskimage build
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'build-diskimage-fedora.yml',
              ref: context.ref,
            });


  wait-for-build-diskimage-almalinux:
    runs-on: ubuntu-latest
    needs: trigger-build-diskimage-almalinux
    steps:
      - name: Wait for build-diskimage-almalinux to complete
        uses: lewagon/wait-on-check-action@v1.3.4
        with:
          ref: ${{ github.ref }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          check-name: 'build-diskimage-almalinux (ubuntu-latest)'
          wait-interval: 10

  wait-for-build-diskimage-centos:
    runs-on: ubuntu-latest
    needs: trigger-build-diskimage-centos
    steps:
      - name: Wait for build-diskimage-centos to complete
        uses: lewagon/wait-on-check-action@v1.3.4
        with:
          ref: ${{ github.ref }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          check-name: 'build-diskimage-centos (ubuntu-latest)'
          wait-interval: 10

  wait-for-build-diskimage-fedora:
    runs-on: ubuntu-latest
    needs: trigger-build-diskimage-fedora
    steps:
      - name: Wait for build-diskimage-fedora to complete
        uses: lewagon/wait-on-check-action@v1.3.4
        with:
          ref: ${{ github.ref }}
          repo-token: ${{ secrets.GITHUB_TOKEN }} 
          check-name: 'build-diskimage-fedora (ubuntu-latest)'
          wait-interval: 10
