name: tailscale-ssh-fedora
run-name: Tailscale SSH with Fedora container

on:
  workflow_dispatch:

jobs:
  dotfiles-test:
    runs-on: blacksmith-4vcpu-ubuntu-2404

    container:
      image: ghcr.io/gbraad-dotfiles/fedora:latest
      options: --privileged
    
    steps:
      - name: Tailscale Action
        uses: gbraad-actions/start-tailscale@v1
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          args: --ssh --accept-dns=false

      - name: Hang around
        run: |
          IP=`tailscale ip -4`
          echo "Use the following command to connect \`tailscale ssh gbraad@${IP}\`"
          sleep infinity
