name: Sync to downstream repo - gbraad-devenv

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: blacksmith-4vcpu-ubuntu-2404

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2

      - name: Push to destination repository
        run: |
          git config --unset-all http.https://github.com/.extraheader
          git remote add downstream https://gbraad:${{ secrets.PAT }}@github.com/gbraad-devenv/dotfiles.git
          git push -f downstream main
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
