name: tailscale-ssh-runner-amd64
run-name: Tailscale SSH with install action

on:
  workflow_dispatch:

jobs:
  dotfiles-test:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    
    steps:
      - name: Workaround - fixes compaudit
        run: |
          sudo chmod go-w /usr/share/zsh/vendor-completions
          sudo chmod go-w /usr/share/zsh

      - name: Remove unwanted stuff
        uses: gbraad-actions/remove-unwanted@v1

      - name: Tailscale
        uses: gbraad-actions/tailscale-action@v1
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          args: --ssh --accept-dns=false --operator=runner
          hostname: dotfiles

      - name: Usage message
        run: |
          IP=`tailscale ip -4`
          echo "Use the following command to connect \`tailscale ssh runner@${IP}\`"

      - name: Create and share userdirs
        run: |
          cd ${{ github.workspace }}
          mkdir -p Projects Documents Downloads
          ln -s ${{ github.workspace }}/Projects  ${HOME}/Projects
          ln -s ${{ github.workspace }}/Documents ${HOME}/Documents
          ln -s ${{ github.workspace }}/Downloads ${HOME}/Downloads
          tailscale drive share projects ${HOME}/Projects
          tailscale drive share documents ${HOME}/Documents
          tailscale drive share downloads ${HOME}/Downloads

      - name: Dotfiles (install from action)
        uses: gbraad-dotfiles/install-dotfiles-action@v1

      - name: Install required virtualization software
        continue-on-error: true
        uses: gbraad-actions/setup-virtualization@v1

      - name: Install containers tools (optional)
        continue-on-error: true
        uses: gbraad-actions/setup-container-tools@v1

      - name: Codium Server
        uses: gbraad-actions/codium-server-action@v1

      - name: Jupyter Notebook
        uses: gbraad-actions/jupyter-action@v1

      - name: Hang around
        run: |
          sleep 18000

      - name: Message user; 1 hour
        run: |
          sudo wall "about 1 hour remaining"
          sleep 1800

      - name: Message user; 20 minutes
        run: |
          sudo wall "20 minutes remaining"
          sleep 1200

      - name: Upload Artifact - Projects
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: projects
          path: ${{ github.workspace }}/Projects/
          retention-days: 1
          include-hidden-files: true
  
      - name: Upload Artifact - Documents
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: documents
          path: ${{ github.workspace }}/Documents/
          retention-days: 1
          include-hidden-files: true

      - name: Upload Artifact - Downloads
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: downloads
          path: ${{ github.workspace }}/Downloads/
          retention-days: 1
          include-hidden-files: true

      - name: Hang around
        run: |
          sleep infinity
